// apps/qwik-test/src/app.jsx
import { component$, Slot } from '@builder.io/qwik';

import { button } from '@repo/styles/button.css';
import {
	actions,
	container,
	content,
	description as descriptionStyle,
	image,
	title as titleStyle,
} from '@repo/styles/card.css';
import { container as headerContainer } from '@repo/styles/header.css';
import { grid } from './app.css';

import qwikLogo from './assets/qwik.svg';

const Button = component$(({ children, ...props }) => (
	<button class={button} {...props}>
		<Slot />
	</button>
));

const Card = component$(({ imageSrc, imageAlt, title, description }) => (
	<div class={container}>
		<img src={imageSrc} alt={imageAlt} class={image} />
		<div class={content}>
			<div class={titleStyle}>{title}</div>
			<div class={descriptionStyle}>{description}</div>
			<div class={actions}>
				<Button>Order This Mouse Now!</Button>
			</div>
		</div>
	</div>
));

export const App = component$(() => {
	return (
		<>
			<div class={headerContainer}>
				<img
					src={qwikLogo}
					alt='Qwik logo'
					style='width: 25px; height: 25px;'
				/>
				<div>SolidJS on Qwik</div>
			</div>
			<div class={grid}>
				<Card
					imageSrc='mouse-dragon-1.png'
					imageAlt='Dragon Face Mouse'
					title='Dragon Face Mouse'
					description='Give our mouse the power of a dragon. This mouse is a powerful mouse that can be used to hunt in the Pinnacle Chamber.'
				/>
				<Card
					imageSrc='mouse-steampunk-2.png'
					imageAlt='Steampunk Mouse'
					title='Steampunk Mouse'
					description='Check out the gears on our steampunk mouse. This mouse means top hat wearing business.'
				/>
			</div>
		</>
	);
});

// apps/web/app/page.tsx
import Image from "next/image";
import { button } from "@repo/styles/button.css";
import {
  container,
  image,
  content,
  actions,
  title as titleStyle,
  description as descriptionStyle,
} from "@repo/styles/card.css";
import { grid } from "./page.css";

const Button = ({ children, ...props }) => (
  <button className={button} {...props}>
    {children}
  </button>
);

const Card = ({ imageSrc, imageAlt, title, description }) => (
  <div className={container}>
    <Image
      src={imageSrc}
      alt={imageAlt}
      width={1024}
      height={1024}
      className={image}
    />
    <div className={content}>
      <div className={titleStyle}>{title}</div>
      <div className={descriptionStyle}>{description}</div>
      <div className={actions}>
        <Button>Order This Mouse Now!</Button>
      </div>
    </div>
  </div>
);

export default function Page() {
  return (
    <div className={grid}>
      <Card
        imageSrc="/mouse-cyberpunk-2.png"
        imageAlt="Cyberpunk mouse"
        title="Odd Cyberpunk Mouse"
        description="What is this thing? Not even we know? But it's cool, right? Is it even useful?"
      />
      <Card
        imageSrc="/mouse-50s.png"
        imageAlt="50s mouse"
        title="Retro Mouse"
        description="Check out this amazing retro gaming mouse. It's like you went back to the 50s!"
      />
    </div>
  );
}
