// apps/web/app/page.tsx
import Image from "next/image";
import { button } from "@repo/styles/button.css";
import {
  container,
  image,
  content,
  actions,
  title as titleStyle,
  description as descriptionStyle,
} from "@repo/styles/card.css";
import { grid } from "./page.css";

const Button = ({ children, ...props }) => (
  <button className={button} {...props}>
    {children}
  </button>
);

const Card = ({ imageSrc, imageAlt, title, description }) => (
  <div className={container}>
    <Image
      src={imageSrc}
      alt={imageAlt}
      width={1024}
      height={1024}
      className={image}
    />
    <div className={content}>
      <div className={titleStyle}>{title}</div>
      <div className={descriptionStyle}>{description}</div>
      <div className={actions}>
        <Button>Order This Mouse Now!</Button>
      </div>
    </div>
  </div>
);

export default function Page() {
  return (
    <div className={grid}>
      <Card
        imageSrc="/mouse-cyberpunk-2.png"
        imageAlt="Cyberpunk mouse"
        title="Odd Cyberpunk Mouse"
        description="What is this thing? Not even we know? But it's cool, right? Is it even useful?"
      />
      <Card
        imageSrc="/mouse-50s.png"
        imageAlt="50s mouse"
        title="Retro Mouse"
        description="Check out this amazing retro gaming mouse. It's like you went back to the 50s!"
      />
    </div>
  );
}

// apps/vue-vesion/src/App.vue
<script setup>
import { container as headerContainer } from '@repo/styles/header.css';
import { grid } from './App.css';

import Card from './components/Card.vue';
</script>

<template>
	<div>
		<div :class="headerContainer">
			<img
				src="./assets/vue.svg"
				alt="Vue logo"
				style="width: 25px; height: 25px"
			/>
			<div>Vue on Vite</div>
		</div>
		<div :class="grid">
			<Card
				imageSrc="mouse-steampunk-3.png"
				imageAlt="Steampunk Super Mouse"
				title="Steampunk Super Mouse"
				description="What the heck is this thing? Is it even usable? You might get cut or something, but it's probably worth it to rock this amazing mouse."
			/>
			<Card
				imageSrc="mouse-star-wars.png"
				imageAlt="Star Wars Mouse"
				title="Star Wars Mouse"
				description="We're gonna get sued by Lucasfilm, but it's worth it for this great looking mouse."
			/>
		</div>
	</div>
</template>
